// Robotito — common object catalog for recognition hints and "show me" requests.
(function(){
  const items = [
    ["book","📚",["libro","libros"],["book","books"],"lectura"],
    ["notebook","📓",["cuaderno","libreta"],["notebook"],"estudio"],
    ["pencil","✏️",["lapiz","lápiz"],["pencil"],"estudio"],
    ["pen","🖊️",["lapicera","boligrafo","bolígrafo"],["pen"],"estudio"],
    ["eraser","🧽",["goma de borrar","goma"],["eraser"],"estudio"],
    ["ruler","📏",["regla"],["ruler"],"estudio"],
    ["backpack","🎒",["mochila"],["backpack"],"estudio"],
    ["scissors","✂️",["tijera","tijeras"],["scissors"],"estudio"],
    ["calculator","🧮",["calculadora"],["calculator"],"estudio"],
    ["globe","🌐",["globo terraqueo","globo terráqueo"],["globe"],"estudio"],
    ["phone","📱",["celular","telefono","teléfono","movil","móvil"],["phone","cell phone","smartphone"],"tecnología"],
    ["laptop","💻",["laptop","computadora portatil","computadora portátil"],["laptop"],"tecnología"],
    ["computer","🖥️",["computadora","ordenador","pc"],["computer","desktop computer"],"tecnología"],
    ["keyboard","⌨️",["teclado"],["keyboard"],"tecnología"],
    ["mouse","🖱️",["mouse","raton","ratón"],["mouse"],"tecnología"],
    ["headphones","🎧",["auriculares","audifonos","audífonos"],["headphones"],"tecnología"],
    ["camera","📷",["camara","cámara"],["camera"],"tecnología"],
    ["television","📺",["television","televisión","tele"],["television","tv"],"tecnología"],
    ["remote","🎛️",["control remoto","mando"],["remote control"],"tecnología"],
    ["watch","⌚",["reloj","reloj de pulsera"],["watch"],"accesorio"],
    ["clock","🕒",["reloj de pared"],["clock"],"hogar"],
    ["lamp","💡",["lampara","lámpara"],["lamp"],"hogar"],
    ["chair","🪑",["silla"],["chair"],"hogar"],
    ["table","🛋️",["mesa"],["table"],"hogar"],
    ["sofa","🛋️",["sofa","sofá","sillon","sillón"],["sofa","couch"],"hogar"],
    ["bed","🛏️",["cama"],["bed"],"hogar"],
    ["door","🚪",["puerta"],["door"],"hogar"],
    ["window","🪟",["ventana"],["window"],"hogar"],
    ["mirror","🪞",["espejo"],["mirror"],"hogar"],
    ["key","🔑",["llave"],["key"],"hogar"],
    ["bottle","🧴",["botella"],["bottle"],"hogar"],
    ["cup","☕",["taza"],["cup","mug"],"cocina"],
    ["glass","🥛",["vaso"],["glass"],"cocina"],
    ["plate","🍽️",["plato"],["plate"],"cocina"],
    ["fork","🍴",["tenedor"],["fork"],"cocina"],
    ["knife","🔪",["cuchillo"],["knife"],"cocina"],
    ["spoon","🥄",["cuchara"],["spoon"],"cocina"],
    ["pan","🍳",["sarten","sartén"],["frying pan","pan"],"cocina"],
    ["pot","🍲",["olla"],["pot"],"cocina"],
    ["fridge","🧊",["heladera","refrigerador"],["refrigerator","fridge"],"cocina"],
    ["microwave","📦",["microondas"],["microwave"],"cocina"],
    ["apple","🍎",["manzana"],["apple"],"comida"],
    ["banana","🍌",["banana","platano","plátano"],["banana"],"comida"],
    ["orange","🍊",["naranja"],["orange"],"comida"],
    ["lemon","🍋",["limon","limón"],["lemon"],"comida"],
    ["strawberry","🍓",["frutilla","fresa"],["strawberry"],"comida"],
    ["grapes","🍇",["uvas","uva"],["grapes"],"comida"],
    ["watermelon","🍉",["sandia","sandía"],["watermelon"],"comida"],
    ["pear","🍐",["pera"],["pear"],"comida"],
    ["peach","🍑",["durazno","melocoton","melocotón"],["peach"],"comida"],
    ["pineapple","🍍",["anana","ananá","piña"],["pineapple"],"comida"],
    ["carrot","🥕",["zanahoria"],["carrot"],"comida"],
    ["tomato","🍅",["tomate"],["tomato"],"comida"],
    ["potato","🥔",["papa","patata"],["potato"],"comida"],
    ["bread","🍞",["pan"],["bread"],"comida"],
    ["cheese","🧀",["queso"],["cheese"],"comida"],
    ["egg","🥚",["huevo"],["egg"],"comida"],
    ["pizza","🍕",["pizza"],["pizza"],"comida"],
    ["hamburger","🍔",["hamburguesa"],["hamburger","burger"],"comida"],
    ["cookie","🍪",["galletita","galleta"],["cookie"],"comida"],
    ["cake","🎂",["torta","pastel"],["cake"],"comida"],
    ["icecream","🍦",["helado"],["ice cream"],"comida"],
    ["dog","🐶",["perro","perra"],["dog"],"animal"],
    ["cat","🐱",["gato","gata"],["cat"],"animal"],
    ["rabbit","🐰",["conejo","coneja"],["rabbit"],"animal"],
    ["hamster","🐹",["hamster","hámster"],["hamster"],"animal"],
    ["mouse-animal","🐭",["raton animal","ratón animal"],["mouse animal"],"animal"],
    ["cow","🐮",["vaca"],["cow"],"animal"],
    ["pig","🐷",["cerdo","chancho"],["pig"],"animal"],
    ["horse","🐴",["caballo","yegua"],["horse"],"animal"],
    ["sheep","🐑",["oveja"],["sheep"],"animal"],
    ["goat","🐐",["cabra"],["goat"],"animal"],
    ["lion","🦁",["leon","león"],["lion"],"animal"],
    ["tiger","🐯",["tigre"],["tiger"],"animal"],
    ["bear","🐻",["oso"],["bear"],"animal"],
    ["panda","🐼",["panda","oso panda"],["panda"],"animal"],
    ["monkey","🐵",["mono"],["monkey"],"animal"],
    ["elephant","🐘",["elefante"],["elephant"],"animal"],
    ["giraffe","🦒",["jirafa"],["giraffe"],"animal"],
    ["zebra","🦓",["cebra"],["zebra"],"animal"],
    ["deer","🦌",["ciervo","venado"],["deer"],"animal"],
    ["fox","🦊",["zorro"],["fox"],"animal"],
    ["wolf","🐺",["lobo"],["wolf"],"animal"],
    ["chicken","🐔",["gallina","pollo"],["chicken","hen"],"animal"],
    ["rooster","🐓",["gallo"],["rooster"],"animal"],
    ["duck","🦆",["pato"],["duck"],"animal"],
    ["penguin","🐧",["pinguino","pingüino"],["penguin"],"animal"],
    ["owl","🦉",["buho","búho","lechuza"],["owl"],"animal"],
    ["eagle","🦅",["aguila","águila"],["eagle"],"animal"],
    ["frog","🐸",["rana"],["frog"],"animal"],
    ["snake","🐍",["serpiente","culebra"],["snake"],"animal"],
    ["turtle","🐢",["tortuga"],["turtle"],"animal"],
    ["fish","🐟",["pez","pescado"],["fish"],"animal"],
    ["dolphin","🐬",["delfin","delfín"],["dolphin"],"animal"],
    ["whale","🐋",["ballena"],["whale"],"animal"],
    ["octopus","🐙",["pulpo"],["octopus"],"animal"],
    ["butterfly","🦋",["mariposa"],["butterfly"],"animal"],
    ["bee","🐝",["abeja"],["bee"],"animal"],
    ["ladybug","🐞",["mariquita","vaquita de san antonio"],["ladybug"],"animal"],
    ["spider","🕷️",["arana","araña"],["spider"],"animal"],
    ["ant","🐜",["hormiga"],["ant"],"animal"],
    ["car","🚗",["auto","coche","carro"],["car"],"transporte"],
    ["bus","🚌",["omnibus","ómnibus","bus","autobus","autobús"],["bus"],"transporte"],
    ["train","🚆",["tren"],["train"],"transporte"],
    ["airplane","✈️",["avion","avión"],["airplane","plane"],"transporte"],
    ["bicycle","🚲",["bicicleta","bici"],["bicycle","bike"],"transporte"],
    ["motorcycle","🏍️",["moto","motocicleta"],["motorcycle"],"transporte"],
    ["boat","⛵",["barco","bote"],["boat"],"transporte"],
    ["truck","🚚",["camion","camión"],["truck"],"transporte"],
    ["ball","⚽",["pelota","balon","balón"],["ball"],"juego"],
    ["soccerball","⚽",["pelota de futbol","pelota de fútbol"],["soccer ball","football"],"juego"],
    ["basketball","🏀",["pelota de basquetbol","pelota de básquetbol","pelota de basket"],["basketball"],"juego"],
    ["tennis","🎾",["pelota de tenis"],["tennis ball"],"juego"],
    ["guitar","🎸",["guitarra"],["guitar"],"música"],
    ["piano","🎹",["piano","teclado musical"],["piano"],"música"],
    ["drum","🥁",["tambor","bateria","batería"],["drum"],"música"],
    ["violin","🎻",["violin","violín"],["violin"],"música"],
    ["microphone","🎤",["microfono","micrófono"],["microphone"],"música"],
    ["shirt","👕",["remera","camiseta"],["shirt","t-shirt"],"ropa"],
    ["pants","👖",["pantalon","pantalón"],["pants","trousers"],"ropa"],
    ["dress","👗",["vestido"],["dress"],"ropa"],
    ["shoe","👟",["zapato","champion","champión","zapatilla"],["shoe","sneaker"],"ropa"],
    ["hat","🧢",["gorra","sombrero"],["hat","cap"],"ropa"],
    ["glasses","👓",["lentes","anteojos","gafas"],["glasses"],"accesorio"],
    ["umbrella","☂️",["paraguas"],["umbrella"],"accesorio"],
    ["toothbrush","🪥",["cepillo de dientes"],["toothbrush"],"baño"],
    ["soap","🧼",["jabon","jabón"],["soap"],"baño"],
    ["towel","🧻",["toalla"],["towel"],"baño"],
    ["flower","🌸",["flor"],["flower"],"naturaleza"],
    ["tree","🌳",["arbol","árbol"],["tree"],"naturaleza"],
    ["leaf","🍃",["hoja"],["leaf"],"naturaleza"],
    ["sun","☀️",["sol"],["sun"],"naturaleza"],
    ["moon","🌙",["luna"],["moon"],"naturaleza"],
    ["star","⭐",["estrella"],["star"],"naturaleza"],
    ["cloud","☁️",["nube"],["cloud"],"naturaleza"],
    ["rainbow","🌈",["arcoiris","arco iris"],["rainbow"],"naturaleza"],
    ["heart","❤️",["corazon","corazón"],["heart"],"símbolo"],
    ["gift","🎁",["regalo"],["gift","present"],"objeto"],
    ["candle","🕯️",["vela"],["candle"],"objeto"],
    ["balloon","🎈",["globo"],["balloon"],"objeto"],
    ["teddy","🧸",["osito","oso de peluche","peluche"],["teddy bear","stuffed bear"],"objeto"],
    ["house","🏠",["casa"],["house","home"],"lugar"],
    ["school","🏫",["escuela","colegio","liceo"],["school"],"lugar"],
    ["hospital","🏥",["hospital"],["hospital"],"lugar"],
    ["store","🏪",["tienda","almacen","almacén"],["store","shop"],"lugar"],
    ["park","🏞️",["parque"],["park"],"lugar"],
    ["beach","🏖️",["playa"],["beach"],"lugar"],
    ["mountain","⛰️",["montana","montaña"],["mountain"],"naturaleza"],
    ["volcano","🌋",["volcan","volcán"],["volcano"],"naturaleza"],
    ["fire","🔥",["fuego","llama"],["fire","flame"],"naturaleza"],
    ["snowflake","❄️",["nieve","copo de nieve"],["snow","snowflake"],"naturaleza"],
    ["snowman","☃️",["muneco de nieve","muñeco de nieve"],["snowman"],"objeto"],
    ["rocket","🚀",["cohete"],["rocket"],"espacio"],
    ["satellite","🛰️",["satelite","satélite"],["satellite"],"espacio"],
    ["planet","🪐",["planeta","saturno"],["planet","saturn"],"espacio"],
    ["earth","🌍",["tierra","planeta tierra"],["earth"],"espacio"],
    ["microscope","🔬",["microscopio"],["microscope"],"ciencia"],
    ["telescope","🔭",["telescopio"],["telescope"],"ciencia"],
    ["magnet","🧲",["iman","imán"],["magnet"],"ciencia"],
    ["testtube","🧪",["tubo de ensayo"],["test tube"],"ciencia"],
    ["dna","🧬",["adn","dna"],["dna"],"ciencia"],
    ["atom","⚛️",["atomo","átomo"],["atom"],"ciencia"],
    ["map","🗺️",["mapa"],["map"],"objeto"],
    ["compass","🧭",["brujula","brújula"],["compass"],"objeto"],
    ["calendar","📅",["calendario"],["calendar"],"objeto"],
    ["envelope","✉️",["sobre","carta"],["envelope","letter"],"objeto"],
    ["paperclip","📎",["clip","sujetapapeles"],["paperclip"],"objeto"],
    ["folder","📁",["carpeta"],["folder"],"objeto"],
    ["bell","🔔",["campana","timbre"],["bell"],"objeto"],
    ["alarm","⏰",["despertador","alarma"],["alarm clock","alarm"],"objeto"],
    ["battery","🔋",["bateria electrica","pila"],["battery"],"tecnología"],
    ["bulb","💡",["bombita","bombilla","foco"],["light bulb"],"tecnología"],
    ["plug","🔌",["enchufe"],["plug"],"tecnología"],
    ["lock","🔒",["candado"],["lock","padlock"],"objeto"],
    ["hammer","🔨",["martillo"],["hammer"],"herramienta"],
    ["wrench","🔧",["llave inglesa","llave de tuercas"],["wrench"],"herramienta"],
    ["gear","⚙️",["engranaje"],["gear"],"objeto"],
    ["cart","🛒",["carrito de compras"],["shopping cart"],"objeto"],
    ["money","💵",["dinero","billete"],["money","banknote"],"objeto"],
    ["coin","🪙",["moneda"],["coin"],"objeto"],
    ["card","💳",["tarjeta","tarjeta de credito","tarjeta de crédito"],["card","credit card"],"objeto"],
    ["crown","👑",["corona"],["crown"],"objeto"],
    ["diamond","💎",["diamante"],["diamond"],"objeto"],
    ["robot","🤖",["robot"],["robot"],"objeto"],
    ["unicorn","🦄",["unicornio"],["unicorn"],"fantasía"],
    ["dinosaur","🦖",["dinosaurio","tiranosaurio"],["dinosaur","t-rex"],"animal"],
    ["dragon","🐉",["dragon","dragón"],["dragon"],"fantasía"],
    ["crocodile","🐊",["cocodrilo"],["crocodile"],"animal"],
    ["shark","🦈",["tiburon","tiburón"],["shark"],"animal"],
    ["crab","🦀",["cangrejo"],["crab"],"animal"],
    ["lobster","🦞",["langosta marina"],["lobster"],"animal"],
    ["parrot","🦜",["loro","papagayo"],["parrot"],"animal"],
    ["flamingo","🦩",["flamenco"],["flamingo"],"animal"],
    ["swan","🦢",["cisne"],["swan"],"animal"],
    ["peacock","🦚",["pavo real"],["peacock"],"animal"],
    ["kangaroo","🦘",["canguro"],["kangaroo"],"animal"],
    ["koala","🐨",["koala"],["koala"],"animal"],
    ["sloth","🦥",["perezoso"],["sloth"],"animal"],
    ["otter","🦦",["nutria"],["otter"],"animal"],
    ["seal","🦭",["foca"],["seal"],"animal"],
    ["llama","🦙",["llama animal"],["llama"],"animal"],
    ["camel","🐪",["camello"],["camel"],"animal"],
    ["rhino","🦏",["rinoceronte"],["rhinoceros","rhino"],"animal"],
    ["hippo","🦛",["hipopotamo","hipopótamo"],["hippopotamus","hippo"],"animal"],
    ["cactus","🌵",["cactus"],["cactus"],"naturaleza"],
    ["mushroom","🍄",["hongo","seta"],["mushroom"],"naturaleza"],
    ["avocado","🥑",["palta","aguacate"],["avocado"],"comida"],
    ["corn","🌽",["choclo","maiz","maíz"],["corn"],"comida"],
    ["broccoli","🥦",["brocoli","brócoli"],["broccoli"],"comida"],
    ["cherries","🍒",["cerezas","cereza"],["cherries"],"comida"],
    ["kiwi","🥝",["kiwi"],["kiwi"],"comida"],
    ["donut","🍩",["dona","donut"],["donut"],"comida"],
    ["chocolate","🍫",["chocolate"],["chocolate"],"comida"],
    ["popcorn","🍿",["pop","pochoclo","palomitas"],["popcorn"],"comida"],
    ["sandwich","🥪",["sandwich","sándwich"],["sandwich"],"comida"],
    ["hotdog","🌭",["pancho","hot dog"],["hot dog"],"comida"],
    ["taco","🌮",["taco"],["taco"],"comida"],
    ["coffee","☕",["cafe","café"],["coffee"],"bebida"],
    ["tea","🍵",["te","té"],["tea"],"bebida"],
    ["juice","🧃",["jugo","zumo"],["juice"],"bebida"],
    ["water","💧",["agua","gota de agua"],["water","water drop"],"bebida"],
    ["triangle","🔺",["triangulo","triángulo"],["triangle"],"forma"],
    ["circle","⭕",["circulo","círculo"],["circle"],"forma"],
    ["square","🟥",["cuadrado"],["square"],"forma"],
    ["blueheart","💙",["corazon azul","corazón azul"],["blue heart"],"símbolo"],
    ["greenheart","💚",["corazon verde","corazón verde"],["green heart"],"símbolo"],
    ["yellowheart","💛",["corazon amarillo","corazón amarillo"],["yellow heart"],"símbolo"]
  ];

  const catalog=items.map(([id,emoji,es,en,category])=>({id,emoji,es,en,category}));
  const norm=s=>String(s||"").toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9\s]/g," ").replace(/\s+/g," ").trim();

  function find(query){
    const q=norm(query);
    let best=null,bestLen=0;
    for(const item of catalog){
      for(const alias of [...item.es,...item.en]){
        const a=norm(alias);
        if((q===a||q.includes(a)||a.includes(q))&&a.length>bestLen){best=item;bestLen=a.length;}
      }
    }
    return best;
  }
  function findByModelLabel(label){
    const q=norm(label).replace(/,/g," ");
    return find(q) || catalog.find(item=>[...item.es,...item.en].some(a=>q.includes(norm(a))));
  }

  window.ROBOTITO_OBJECTS={catalog,find,findByModelLabel};
})();